custom archive type needs extract_path
archive type's extract_path doesn't have a default parameter and needs to be set (see https://github.com/voxpupuli/puppet-archive/blob/master/lib/puppet/type/archive.rb#L71-L78). If I don't set one I get the following error when trying to use this module:

Error: Failed to apply catalog: No title provided and :file is not a valid resource reference